# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-01 03:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bands', '0002_auto_20160401_0315'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='album',
            name='date',
        ),
        migrations.AddField(
            model_name='album',
            name='year',
            field=models.IntegerField(max_length=4, null=True),
        ),
    ]
