# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-02 23:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bands', '0003_auto_20160401_0325'),
    ]

    operations = [
        migrations.AlterField(
            model_name='album',
            name='year',
            field=models.IntegerField(),
        ),
    ]
