# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-08 02:28
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bands', '0007_auto_20160404_0056'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='album',
            name='location',
        ),
        migrations.RemoveField(
            model_name='band',
            name='location',
        ),
    ]
