# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-08 02:49
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cities', '0001_initial'),
        ('bands', '0008_auto_20160408_0228'),
    ]

    operations = [
        migrations.AddField(
            model_name='album',
            name='location',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='cities.City'),
        ),
        migrations.AddField(
            model_name='band',
            name='location',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='cities.City'),
        ),
    ]
